version: "3.7"

services:
  phone-php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: phone-php
    ports:
      - 9000:9000
    volumes:
      - ./main:/var/www/html
    depends_on:
      - phone-mysql
    networks:
      - appnetwork

  phone-mysql:
    image: mysql
    container_name: phone-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xNPckYC6ihJcztm5
      - MYSQL_DATABASE=cydia
      - MYSQL_TCP_PORT=3307
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3307
    networks:
      - appnetwork

  phone-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: phone-nginx
    restart: always
    ports:
      - 8585:8585
      - 8888:8888
    volumes:
      - ./nginx/log:/var/log/nginx
    depends_on:
      - phone-php
    networks:
      - appnetwork

networks:
  appnetwork:
    name: inventory-phone-network
    external: true